* Introduction

MulityGet to speed up downloading from server.

It provides a library named libmget and a sample app named tmget.


You can download it from:[[http://github.com/yangyingchao/mget][ here .]]

* Use mget in gentoo

You can set mget to be used to fetch resources from internet, just update you
make.conf:

#+BEGIN_SRC conf
FETCHCOMMAND="/usr/bin/mget -j 10 -o \"\${DISTDIR}/\${FILE}\" \"\${URI}\""
RESUMECOMMAND="${FETCHCOMMAND}"
#+END_SRC

* About MTU

Remember to change you MTU to larger value (for example 7200), it MAY help.

#+BEGIN_SRC text
ifconfig eth0 mtu 7200
#+END_SRC

* SSL Support

 It uses GnuTls to implement SSL support...

* TODO:

** Reschedule connections if some connections are ide....

** Change structure.

 so we don't need to update libmget.c when adding support to new protocols

*** Add "protocols" subfolder.

*** Move http/ftp codes into subfolder of "protocols".

*** Each file (http.c/ftp.c) shall provide a function to register itself into libmget.

*** Write a script to register those protocol  handlers..
